name: CI-Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint on all Python files
      run: |
        find . \( -path "./.git" -o -path "./__pycache__" -o -path "*/__pycache__" -o -path "*/venv" -o -path "*/env" -o -path "*/.venv" \) -prune -o -name "*.py" -print0 | xargs -0 -r pylint

    - name: Run pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        if [ -d "tests" ] && [ "$(find tests -name '*.py' -not -name '__init__.py' | wc -l)" -gt 0 ]; then
          pytest --tb=short
        else
          echo "No test files found, skipping pytest"
        fi
